import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" type="image/png" href="/images/favicon.ico" />
        <style>{`
          .bg-custom-radial {
            background: radial-gradient(
              circle at center,
              rgba(250, 218, 221, 0.4) 0%,
              rgba(232, 218, 253, 0.4) 30%,
              rgba(218, 232, 253, 0.4) 60%,
              #ffffff 90%
            );
          }
        `}</style>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-custom-radial`}
      >
        {children}
      </body>
    </html>
  );
}